# Generated by Django 2.0.2 on 2018-02-25 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('picture', models.ImageField(upload_to='img/tafaha')),
                ('answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tafaha.Answer')),
            ],
        ),
    ]
