# Generated by Django 2.0.2 on 2018-02-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tafaha', '0002_answer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='picture',
            field=models.ImageField(upload_to='Noneimg/tafaha'),
        ),
    ]
