# Generated by Django 2.0.2 on 2018-02-28 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tafaha', '0005_auto_20180227_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='test',
            name='answers',
        ),
        migrations.AddField(
            model_name='answer',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tafaha.Test'),
            preserve_default=False,
        ),
    ]
