# Generated by Django 2.0.2 on 2018-02-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tafaha', '0006_auto_20180228_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='picture',
            field=models.ImageField(null=True, upload_to='img/tafaha'),
        ),
    ]
