# Generated by Django 2.0.2 on 2018-03-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tafaha', '0007_answer_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='text',
        ),
        migrations.AddField(
            model_name='test',
            name='height',
            field=models.IntegerField(default=400),
        ),
        migrations.AddField(
            model_name='test',
            name='width',
            field=models.IntegerField(default=800),
        ),
        migrations.AddField(
            model_name='test',
            name='x',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='test',
            name='y',
            field=models.IntegerField(default=100),
        ),
    ]
