# Generated by Django 2.0.2 on 2018-03-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tafaha', '0008_auto_20180324_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='genre',
            field=models.CharField(choices=[('f', 'female'), ('m', 'male')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
